mex mex_cos.c ../fm_util.c ../fm_sincos.c '-I../'
mex mex_sin.c ../fm_util.c ../fm_sincos.c '-I../'
mex mex_log.c ../fm_util.c ../fm_lnlog10.c '-I../'
mex mex_log10.c ../fm_util.c ../fm_lnlog10.c '-I../'
mex mex_exp.c ../fm_util.c ../fm_exp.c '-I../'
mex mex_pow.c ../fm_util.c ../fm_pow.c '-I../'
mex mex_asin.c ../fm_util.c ../fm_asincos.c ../fm_sqrt.c '-I../'
mex mex_acos.c ../fm_util.c ../fm_asincos.c ../fm_sqrt.c '-I../'
mex mex_sqrt.c ../fm_util.c ../fm_sqrt.c '-I../'
mex mex_tan.c ../fm_util.c ../fm_tancotan.c '-I../'